export const useStyles = {
  root: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: '#F8F9FAFF',
    color: 'black',
    top: 0,
    width: '100%',
    height: '91px',
  } as React.CSSProperties,
  logo: {
    marginLeft: '41px',
    fontSize: '36px',
    fontFamily: 'Epilogue',
    color: 'red',
  } as React.CSSProperties,
  search: { display: 'flex', alignItems: 'center' } as React.CSSProperties,
  register: {
    width: '93px',
    height: '52px',
    color: 'white',
    fontSize: '14px',
    fontFamily: 'Inter',
    background: 'black',
    opacity: 1,
    borderRadius: '12px',
  } as React.CSSProperties,
  login: {
    width: '77px',
    height: '52px',
    color: 'white',
    fontSize: '14px',
    fontFamily: 'Inter',
    background: 'red',
    opacity: 1,
    borderRadius: '12px',
  } as React.CSSProperties,
};
